### ISSUE TITLE
Adding option for adding a CA

### ISSUE THREAD

**Issue by noahwaldner** [compwright/passport-saml-metadata#17]
For use in a corperate environment the option for a custom CA should be added.

At the Moment the Error "UNABLE_TO_VERIFY_LEAF_SIGNATURE" appears.

**Comment by ronanquillevere** [comment]
We should be able to configure superagent behavior as this is a dependency of the lib

**Comment by compwright** [comment]
@noahwaldner @ronanquillevere I've released v2.1.0, which uses axios under the hood. You can pass in extra configuration, or a pre-configured axios instance via the `client` parameter.

See axios configs here: https://github.com/axios/axios#request-config

In particular note `httpsAgent` which you can configure like this: https://github.com/axios/axios#request-config

**Comment by ronanquillevere** [comment]
Great thank you !
