### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by icer9955** [compwright/passport-saml-metadata#2]
Trying to use this and my webpack/babel build is complaining about an illegal assignment.

```
ERROR in server.js from UglifyJs
    Invalid assignment [./node_modules/passport-saml-metadata/node_modules/node-forge/js/util.js:1885,0]

--> define = function(ids, factory) {
```

This is coming from an outdated digitalbazaar/forge#353, which is in turn coming from an outdated auth0/node-xml-encryption#28, which is coming from an outdated bergie/passport-saml#222.

Long term, it may be best to declare `passport-saml` as a peerDependency instead.  But for now, better to just update.

**Comment by icer9955** [comment]
Awesome, thanks for bringing that in so quickly.  When do you think you'll be able to cut a new release version for npm?

**Comment by compwright** [comment]
Published as 1.4.0 - thanks for the submission!

**Comment by mariano1986** [comment]
Hello! I have the same issue but i don't understand how to fix it, i install and update all the packages you mention but i still got the error.
I'm trying the package in vue-js.
If someone could help me i really apreciate it!

**Comment by icer9955** [comment]
The `node-forge` package had the bug that was reported in this ticket.  Now that this project has updated the dependencies, it's not longer bringing in the old `node-forge` that is causing this error.  I've confirmed that myself.

`npm list node-forge`

Run that command and it'll tell you what packages you have installed that are using node-forge, as well as the version number that the package is bringing in.  Chances are, your project is pulling in an out-dated version of node-forge through a different package than `passport-saml-metadata`.  Find the project that has an old version of node-forge, then get them to update their dependencies.

**Comment by mariano1986** [comment]
Finally i made it! The problem was with nod3des module, it uses the node-forge 0.6.45, so i change the dependence version from module's package.json to 0.7.5, then install this version of node-forge and the error gone :D!!
Thank you icer9955 :+1:
