### ISSUE TITLE
Dependency to xmldom lib version which has security issues

### ISSUE THREAD

**Issue by kaskelotti** [compwright/passport-saml-metadata#32]
The project has a dependency to xmldom lib version 0.4.0, which has a security issue. This is already fixed in the latest passport-saml lib from where the fix should come here also automatically I guess. It's still probably best to ensure this and use version 0.5.0 of xmldom

For details, see: https://github.com/xmldom/xmldom/security/advisories/GHSA-h6q6-9hqw-rwfv

**Comment by compwright** [comment]
Released as v2.4.1

**Comment by compwright** [comment]
@kaskelotti thank you for reporting this issue! If this package has been helpful to you, please consider [sponsoring](https://github.com/sponsors/compwright).
