### ISSUE TITLE
remove the dependency on passport-saml, or upgrade it to @node-saml/passport-saml

### ISSUE THREAD

**Issue by ghusse** [compwright/passport-saml-metadata#39]
Hello,

`passport-saml` has recently been deprecated in favor of `@node-saml/passport-saml` and `@node-saml/node-saml`. Is it possible to either remove the dependency on `passport-saml` from `passport-saml-metadata` or upgrade it to the latest version ?

**Comment by compwright** [comment]
@ghusse fixed, released in v3.0.0

**Comment by ghusse** [comment]
Wow, so fast! Thanks a lot
