### ISSUE TITLE
A file extension must be provided when using the import keyword to resolve relative or absolute specifiers.

### ISSUE THREAD

**Issue by zubozrout** [compwright/passport-saml-metadata#42]
When trying to run a project using `passport-saml-metadata` I am getting the following error:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/src/app/node_modules/lodash/camelCase'
imported from /usr/src/app/node_modules/passport-saml-metadata/dist/index.mjs
Did you mean to import lodash/camelCase.js?
```

It seems that based on docs all imports should include file extensions, which seems not to be the case unfortunately though:
https://nodejs.org/api/esm.html#mandatory-file-extensions

Could you please have a look at this and try to fix it?
Thank you very much.

**Comment by thomasdarimont** [comment]
I just stumbled upon this very same issue today.
@compwright I just created a PR with a fix.
