### ISSUE TITLE
Please expose #query or #doc

### ISSUE THREAD

**Issue by dominykas** [compwright/passport-saml-metadata#44]
A similar request has already been made in https://github.com/compwright/passport-saml-metadata/issues/40.

We're still on an earlier version of `passport-saml-metadata`, and we have at least four different calls to `query()`. I do not have enough context to understand whether they make sense to be wrapped as explicit methods, but my gut is telling me that `query()` is probably just easier for everybody?

Would you reconsider exposing it? I'm happy to PR the documentation for it, if that's the only thing holding it back.

Thanks!

**Comment by compwright** [comment]
@dominykas sure, feel free to submit a PR.
